### ISSUE TITLE
Cake not restoring hunger like Minecraft

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#105]
According to the Minecraft wiki "A single slice restores 2 hunger ". 
Right now it restores 1 hunger. 

Being that the hunger count isn't equivalant, maybe up it to 1.5 hunger instead of 1.

**Comment by kwadroke** [comment]
I believe the wheat that is needed to be used could make bread and would restore more.

**Comment by Wuzzy2** [comment]
The hunger count is equivalent, I have fixed the hunger mod already so that MCL2 recognized hunger levels between 0 and 20. It's not between 0 and 30 anymore, as in earlier versions. The hunger mod is not `hbhunger` anymore, but `mcl_hunger` (I heavily modified `hbhunger` just for MCL2).

I also don't see any issue with the cake. I always get 2 hunger points restored.

Note that 1 hunger point = 0.5 hunger icons!

What's wrong about bread? You can craft it with 3 wheat in a row, just like in Minecraft. And it restores 5 hunger points, just like in Minecraft.

I'm leaning towards closing this issue as invalid.

**Comment by kwadroke** [comment]
Nothing wrong with the bread. It just seems to be more work with less results to make the cake than just using the wheat to make the bread. Just seemed to be weaker than I remember from Minecraft.

I'll have to watch the video on cakes again. It's been a while since I played Minecraft itself as I stopped playing it when 1.8.x came out.

Wasn't aware how the hunger point count worked.

I'll close it, but will research to make sure I'm comparing apples to apples and not getting things confused.
If it's still doesn't seem right, I'll reopen.
