### ISSUE TITLE
sign has wrong model and textures

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#107]
@Wuzzy2 fix [sign.zip](https://github.com/Wuzzy2/MineClone2-Bugs/files/805240/sign.zip)

creddit to 22i and me for fixing the mapping

**Comment by tobyplowy** [comment]
@Wuzzy2 ping

**Comment by Wuzzy2** [comment]
There is no such thing as a “wrong” texture. I'm too stupid/lazy to use `.blend` files.
Besides, I actually need 16 orientations of the sign, so 2 sign models are not enough.
I'm pretty sure this number of 16 orientations can be reduced because of `facedir`.

I'm not sure if I can use these models in this form, especially without any context given.

The whole signs mod needs a complete rework anyway, it's basically a leftover from the old MineClone subgame.

Note:
The next time someone posts a “wrong texture” issue without context, I'm going to close it as invalid. I'm okay with comments about *low quality* or broken textures, but then please tell me what is “wrong” or “bad” about the existing textures.

**Comment by tobyplowy** [comment]
@Wuzzy2 It Doesn't Use the same mapping system as Minecraft (MC texturepacks will not be compatible unless you wanna spend 5 minute's fixing the textures and Even then they will have to be stressed Because of The model is not the correct shape) but it was mostly the model that anoyed me

**Comment by Wuzzy2** [comment]
OK, “texture mapping is not the same as in Minecraft” IS a valid issue. Thanks.
Please mention these details directly, because just saying “wrong texture” is not enough.

**Comment by Wuzzy2** [comment]
Waiting for https://github.com/22i/amc/issues/14.

**Comment by Wuzzy2** [comment]
Signs now use models and textures.
Fixed!
