### ISSUE TITLE
Eating raw chicken..

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#109]
Eating raw chicken has a 30% chance of inflicting food poisoning.

**Comment by WSDguy2014** [comment]
Yeah, should get a hunger effect.

**Comment by Jaen-Minetest** [comment]
Yeah, but since it does not currently do anything when you eat raw chicken, I'm just pointing it out.

**Comment by Wuzzy2** [comment]
Confirmed. Will be added when MineClone 2 gets status effects.

**Comment by WSDguy2014** [comment]
Also spider eyes are should get poison effect and it's not marked to WIP in subgame version 0.13.0

**Comment by Wuzzy2** [comment]
Technically, everything in MineClone 2 is WIP. :-)
The items marked “WIP” are just the items for which the core function is still missing, as a friendly reminder to the player, like a “Don't expect too much from this item”. The opposite is not true: *not* having the “WIP” marker does not imply the item is 100% finished. :P

A basic stupid food poisoning system is already finished in `master` and works for rotten flesh, poisonous potato, spider eye and pufferfish. And yes, the spider is also clearly WIP (fixed) because of status effects.

**Comment by Wuzzy2** [comment]
Raw chicken now inflicts food poisoning as of 0.19.0.
