### ISSUE TITLE
Bed texture/model on underneath looks wrong in subgame version 0.13.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#117]
![screenshot_20170301_173155](https://cloud.githubusercontent.com/assets/13905392/23466907/26a8e6ae-fea5-11e6-9b70-8ab4892f8111.png)

**Comment by Wuzzy2** [comment]
Confirmed. But Minecraft is only slightly better, to be honest. It looks ugly in Minecraft, too. :-/

Maybe the bed should be turned into 3D style instead of using flat textures. I wonder if this is possible without breaking the texture packs.

The “real” (and ugly) Minecraft style would probably require me to use meshes, which I would hate to do.

In any case, this is low priority.

**Comment by Wuzzy2** [comment]
Fixed. MCL2 now uses 3D “feet”.

**Comment by WSDguy2014** [comment]
Good. And it should be a block entity, says on Minecraft Wiki website.

**Comment by Wuzzy2** [comment]
:unamused: 
I think I have the final word on the implementation details. :stuck_out_tongue: 
There is no such thing as a “block entity” in Minetest.
