### ISSUE TITLE
Eating rotten flesh, does not get achieve in subgame version 0.15.0

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#145]
@Wuzzy2, Why you add more achievements that didn't exist on PC version in Minecraft?
You should add optional mod for MineClone 2, to add more achievements?

**Comment by WSDguy2014** [comment]
Same thing as cooked porkchop (tested) and cooked rabbit (untested).

**Comment by WSDguy2014** [comment]
Another problem is crafting crafting table in 2x2 crafting grid, does not get achievement.

**Comment by kwadroke** [comment]
I wasn't able to get the achievement for cooked rabbit.

**Comment by Wuzzy2** [comment]
Ooops. Those additional achievements are in other editions of Minecraft (XBox, PS, etc.). Since they're buggy, they should be removed anyway.

The crafting table achievement is indeed broken. I broke it shortly before release! :-(
I pushe a fix now.

The eating achievements only work when you have more than 1 item of the same kind in the hand. Haha, this is dumb. Those have to be removed anyway, so no big deal.

**Comment by Wuzzy2** [comment]
Benchmarking is fixed.
All non-PC achievements have been disabled, so Pork Chop, Rabbit Season and Iron Belly are gone as well.

All achievements with reported bugs have been fixed or remove. Closing.
