### ISSUE TITLE
Missing very first achievement

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#166]
In Minecraft, the first achievement you usually get is Taking Inventory by pressing 'e' but for Minetest we press 'i'. Currently, the first achievement is Getting Wood, but could you add Taking Inventory before it? pressing 'i' is fine. 

Reference: http://minecraft.gamepedia.com/Achievements

Also, would be nice if achievements had prerequisites like vanilla Minecraft so that if you skipped Taking Inventory and punched a tree, you would not get the Getting Wood achievement until you get the Taking Inventory achievement.

**Comment by Wuzzy2** [comment]
Closing as invalid because it contains two distinct features in one. No big deal.
I split this issue in two issues because you both mentioned valid missing features.
Tracking continues in #167 and #168.

Currently, the order of achievements is completely without logic.

About Taking Inventory: The reason why this is not implemented is because I have no freaking idea when the player actually opens the inventory. Surprisingly, there doesn't seem to be a direct callback for that. :-/
