### ISSUE TITLE
That's racist imagery in subgame version 0.16.0?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#172]
Please, change these 2 textures for magenta and white glazed terracotta.
![screenshot_20170330_224625](https://cloud.githubusercontent.com/assets/13905392/24523395/9629257c-159b-11e7-89cd-81bde6740621.png)

According to:
https://bugs.mojang.com/browse/MC-113377
https://bugs.mojang.com/browse/MC-113844

Because textured changed for cyan, magenta, orange, and white glazed terracotta in Minecraft (1.12) snapshot 17w13a, to remove offensive imagery.

@Wuzzy2, add for cyan and orange glazed terracotta (both are must be 2nd version texture for 32x32) soon.

**Comment by Wuzzy2** [comment]
I'm waiting for the Faithful texture pack to update.

**Comment by Wuzzy2** [comment]
Will be fixed, because Minecraft fixes this. To be honest, I think people are overreacting because of this.

Arrows are considered nazi symbology? Come on! Yes, I saw the comparison picture but I still think some people desperately WANT to see nazi symbology.

Nazi symbols are harmless. What people should be concerned about is the nazi ideology.

**Comment by tobyplowy** [comment]
> I think people are overreacting because of this

I agree

**Comment by Wuzzy2** [comment]
Fixed in 92479866dee537de6772628b3c4f11f6ff0e0147.
