### ISSUE TITLE
Buttons not triggering doors when pressed

### ISSUE THREAD

**Issue by Jaen-Minetest** [Wuzzy2/MineClone2-Bugs#174]
Stone and wooden buttons currently do not trigger doors when pressed. This was tested by placing a button on a block next to an iron door. When button is pressed the door should open allowing a player enough time to pass through the door then close again. Both buttons should work for all door types.

**Comment by Bu-Gee** [comment]
I've done some messing with Redstone and it looks like most (all?) blocks do not transmit Redstone signal except for the case when there is a Redstone torch on that block.  This is even in the case where they are "hard" powered with a repeater.

**Comment by Jaen-Minetest** [comment]
Well, in Minecraft, buttons next to doors do not require any redstone to function. I noticed that stone and wooden pressure plates on ground next to doors currently work, well sort of. Stepping on a pressure plate will open a door, but the door will stay open until you step on the pressure plate again. In Minecraft, when you either press a button next to a door or step on a pressure plate next to a door, the door will open for a few seconds then close without having to re-press button or re-step on the pressure plate. I know buttons are not fully implemented currently, and I was just pointing out what I found while testing.

**Comment by dawgdoc** [comment]
Just started trying to use the Redstone yesterday and discovered the button issue while trying to place an iron door in a survival world. I found a work around that may get people by for the time being. I was attempting to build a button activated iron door according to the instructions at 1:52 into [this video](https://www.youtube.com/watch?v=3lVPHYS28hc) 

I used the Redstone, Redstone torches, and Redstone repeater as directed. The button placed next to the door did nothing, however a pressure plate in front of the door did work, as did one inside the door. After finding this issue, and the linked **The Ultimate Redstone Issue**, I went back to creative to see what I could learn.  

- I took all of the Redstone out and the pressure plates continued to work. The button continued to not work.

- I built another doorway with the Redstone items as directed. Instead of placing the iron door as normal, I placed it 'sideways' so that when 'open' the door was obstructing the doorway and when 'closed' it was not. Both the button and pressure plate opened and closed the door.  The button was placed as in the video, but I had to move the pressure plate forward so that it was in the doorway. 

- I removed the Redstone items from this second 'sideways' doorway and then tested. Both the button and pressure plate continued to function. The same held true when I built a new door of this type that had never had Redstone placed. 

My understanding from the video was that the Redstone items were used so that the doors would not close before you could get through the doorway. None of the doors I built closed on their own, no matter how long I waited. They all required activation from a button or a pressure plate to close, confirming what Jaen-minetest stated. 

First image is of doorway with nonFunctioning button, whether or not Redstone items were placed
![screenshot_mcl2-nonfnctioningbutton](https://user-images.githubusercontent.com/26846591/31428615-04255c5c-ae31-11e7-8150-2c1e8b5e6737.png)
Second image is of doorway with Functioning button, whether or not Redstone items were placed.
![screenshot_mcl2_functioningbutton](https://user-images.githubusercontent.com/26846591/31428654-27955a2a-ae31-11e7-9948-094f2b4b34b5.png)

**Comment by Wuzzy2** [comment]
I have finally reworked the redstone rules entirely, and this bug has been fixed along the way.
