### ISSUE TITLE
the armorstand doesn't use the inventory image for the wield texture

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#230]
http://media-minecraftforum.cursecdn.com/attachments/122/891/dw2.png

**Comment by kingoscargames** [comment]
should i stop reporting things related to textures?

**Comment by Wuzzy2** [comment]
No. Thanks for your time.

Fixed in 84d6015084a4d5f9b3a427e7940bd10f36e6406c.

But note I want to eventually replace all textures with 16×16.
If you want to really help this project, I would be very grateful if you could name me (just **name** me) any good free/libre 16×16 Minecraft texture pack. See also: https://github.com/Wuzzy2/MineClone2-Bugs/issues/76

**Comment by kingoscargames** [comment]
i know about the 16x16 textures but i dont know any texture/resourcepack
