### ISSUE TITLE
“Failed to update cost map”

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#26]
I often get the error message “Pathfinder: failed to update cost map” when I'm around mobs. 

Oh god, this is annoying as hell. What on Earth is causing this?

Any comments appreciated!

0.10.0

**Comment by Bu-Gee** [comment]
The likely culprit is in mods/ENTITIES/mobs/api.lua line 844 in the find_path() call.

It looks like it is searching in a radius of 16 blocks.  You might want to see if upping that amount helps any.  You may want to also mess with the 2 blocks jump and 6 blocks drop amounts to see if that helps too.

**Comment by kwadroke** [comment]
I've been seeing this message too. Seems to be mobs.

**Comment by Wuzzy2** [comment]
Oh, the pathfinding seemed to be way out of date.
Fixed jumping height, distance and drop height, totally ignoring the mob properties. This is clearly wrong.
Also, the Dijkstra algorithm instead of A* search used for some reason … (lol)

I fixed these other issues.

Let's see if this also gets rid of the error messages.

I suspect the error messages come from the engine. The error message sounds like the pathfinding failed somehow. But no reason to spam the console log with this, then. It might make more sense to just return `false` or something.

If I don't see this error in the next couple of days again, I consider it fixed.
But I should also research into why this error message appeared in the first place, because it seems clearly out of place.


Thanks for the research you put into this. :-)

**Comment by Bu-Gee** [comment]
It is definitely due to mobs and it is 100% definitely coming from the engine.  Here is a link to the line of code that is generating it:

https://github.com/minetest/minetest/blob/master/src/pathfinder.cpp#L758

I don't know why the message is compulsory because they appear to suppress other messages in that section of code.  AFAICT, it is in there to be modder abuse.  That is a message that shouldn't pop up unless you're running a debugging version of minetest.  

I don't know if this is something you should send upstream to be fixed, but if it were up to me, that message would be suppressed unless debugging.

**Comment by Wuzzy2** [comment]
Thank you. I guess I will file an issue to Minetest today.

**Comment by Bu-Gee** [comment]
This message is still popping up as of the GIT pull as of around 18:00, on 12 March.

**Comment by Wuzzy2** [comment]
Thankfully, someone already posted a Minetest issue for this:
https://github.com/minetest/minetest/issues/5218
I finally gave my two cents to it.

**Comment by Wuzzy2** [comment]
Okay, now that this is clearly a bug in Minetest *only*, I close this issue.
