### ISSUE TITLE
"cant interact with things and entities behave strange" bug

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#282]
I have "house" (a hole in the ground with double walls around it on the surface) and when a mob tries to attack me but cant go through the wall everything stops working and i cant interact and all entities behave strange (walking in one direction forever and items teleporting back sometimes) untill i reopen the gamem
I will post screenshots later i am on mobile right now not on my pc.

**Comment by kingoscargames** [comment]
*game.

**Comment by kingoscargames** [comment]
My "house":
![screenshot_20170614_201643](https://user-images.githubusercontent.com/29333817/27147885-b09f8aca-513e-11e7-9e3a-5753679dbc6f.png)

**Comment by leorockway** [comment]
As I mentioned in the forum, I'm pretty sure this is an issue with pathfinder for the mobs.

**Comment by leorockway** [comment]
I wonder if using New Pathfinder would help with the pathfinder issue: https://forum.minetest.net/viewtopic.php?f=9&t=17406

**Comment by leorockway** [comment]
By the way, this is most likely a duplicate of https://github.com/Wuzzy2/MineClone2-Bugs/issues/189

**Comment by kingoscargames** [comment]
You didnt say anything about entites glitching (only that they fly).

**Comment by Wuzzy2** [comment]
Can you please give me the last 100 lines (or so) of `debug.txt` when this happens?

**Comment by kingoscargames** [comment]
I am not on my pc right now

**Comment by kingoscargames** [comment]
I cant even play with only peacefull mobs

**Comment by kingoscargames** [comment]
it doesnt leave anything in debug.txt

**Comment by leorockway** [comment]
@kingoscargames 
> You didnt say anything about entites glitching (only that they fly).

I didn't report that bug. I never actually saw anything fly like in that bug report, but I do get what you're reporting here and it coincides with the pathfinder issue.

**Comment by Wuzzy2** [comment]
Did you have any mods activated at the time when this happened?

**Comment by kingoscargames** [comment]
One that ads unbreakable leather armir but it also does it without it.
(And the ones in the game)

**Comment by kingoscargames** [comment]
9

**Comment by kingoscargames** [comment]
Why is my touch screen so ******* stupid

**Comment by leorockway** [comment]
I tried the Lua pathfinder I mentioned in my previous post ( https://forum.minetest.net/viewtopic.php?f=9&t=17406 )

I had to adjust a few things, but I made it work. It tries to write path.txt outside of the world directory and mod security forbids that. So line 172 of init.lua on that mod needs to be modified (it's a very simple fix).

I commented out the minetest.find_path (line 943 of init.lua in the mobs mod) and added this:
`self.path.way = pathfinder.find_path(s, p1, self, dtime)` 

I tried playing with this Lua pathfinder for quite a while and I didn't have any of this issues reported here. I do see quite a few timeouts (printed by Lua pathfinder), but it seems that while the the default pathfinder blocks further processing, this Lua one doesn't. Maybe the default pathfinder should use threading or something, because as it is it's clearly an issue (I haven't looked at the code for default pathfinder, though). This probably only affects older computers and that's why it might be hard to replicate for some people.

**Comment by Wuzzy2** [comment]
Can you please try to reproduce this bug with Minetest Game + Mobs Redo?

**Comment by leorockway** [comment]
I don't remember if I tried reproducing it in Minetest Game or not. I'll go ahead and try that and report back.

**Comment by leorockway** [comment]
Interestingly enough, with vanilla Minetest Game (adding only mobs_redo and mc_mobs), I can't replicate the issue. I do get some "Pathfinder: failed to update cost map" warnings, but they don't make doors, chests, etc unusable. I also get way fewer of those warnings.

**Comment by kingoscargames** [comment]
This doesn't happen to me anymore.
