### ISSUE TITLE
Inventory breaks when using worldedit_gui

### ISSUE THREAD

**Issue by Gerold55** [Wuzzy2/MineClone2-Bugs#284]
When using the creative inventory you are on one tab but when you try to click on another tab it glitches and you can't scroll through the menu because of the bug.
![screenshot 19](https://user-images.githubusercontent.com/13843095/27191176-05db257c-51c5-11e7-84a6-ace093d828d9.png)

**Comment by Wuzzy2** [comment]
Please tell exactly, step by step, what you did, beginning from creating the world until this happened.
Also, are there any warnings or error messages in `debug.txt` after this happened?

I have currently a hard time to reproduce this bug.

**Comment by kingoscargames** [comment]
I had glutches when using wordledit

**Comment by kingoscargames** [comment]
I couldnt switch to survival inventory in creative

**Comment by Wuzzy2** [comment]
Why didn't you say “WorldEdit” from the start? Bug confirmed. xD

The offending mod is `worldedit_gui`, to be precise. Disable `worldedit_gui`, then it works again.

I'll check if WorldEdit offers some sort of compability layer. If not, I will close this as “won't fix” and officially declare incompability with `worldedit_gui`.

**Comment by Gerold55** [comment]
It was because I had just realized it when someone else commented basically the same thing

**Comment by Wuzzy2** [comment]
MineClone 2 now writes an error message when `worldedit_gui` has been found and advices to disable the mod.

Not a real solution, but at least players learn now how to fix this.

**Comment by Wuzzy2** [comment]
Okay, I have now looked into the WorldEdit code and documentation.
Indeed no compability layer is offered at all. So the fact that the inventory is broken by `worldedit_gui` can not be fixed in MineClone 2.

I close this bug as “won't fix”. The error message will be kept.

Please report a bug to the WorldEdit maintainers and complain about incompability with the mod `mcl_inventory` in MineClone 2.
