### ISSUE TITLE
Double item names when selecting it.

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#317]
![screenshot_20170704_102223](https://user-images.githubusercontent.com/29333817/27821607-1d1c8e82-60a3-11e7-8082-5121f01d1058.png)

**Comment by Wuzzy2** [comment]
Try to delete the entire MineClone 2 directory and re-extract the zip archive.
Also, disable all mods.

Then, tell me if it still happens.

**Comment by kingoscargames** [comment]
I deleted it and now it works, i don't know what the problem was.

**Comment by Wuzzy2** [comment]
I'm pretty sure the problem was that you just extracted the new MCL2 version over the existing directory.
The problem with this is that this only works as long I only add or change files in MCL2.
If I delete a file in MCL2, it won't get deleted for you because you only extract the Zip file.

In this case, I have renamed the mod which created the item names. For you this meant that you had the same mod twice, but under different names.

The easy solution to problems like this is to delete the subgame directory before updating.

**Comment by kingoscargames** [comment]
ok
