### ISSUE TITLE
16×16 textures for glazed terracotta

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#336]
The glazed terracotta needs 16×16 textures.

Currently these blocks are still using the 32×32 textures from Faithful.
Pixel Perfection does not have glazed terracotta textures (yet).

**Comment by MysticTempest** [comment]
Hi Wuzzy2,

I recently made some 16x16 textures for the glazed terracotta. I used references to get them pretty close to the originals. But, are otherwise done from scratch, & under a CC-BY-SA 4.0 license.

Here's a preview:
![glazedterracotta_2x2_preview](https://user-images.githubusercontent.com/32621758/31461030-d272d010-ae8d-11e7-8acc-30490589dea8.png)

Download:
[glazed_terracotta.zip](https://github.com/Wuzzy2/MineClone2-Bugs/files/1376846/glazed_terracotta.zip)

**Comment by Wuzzy2** [comment]
Thanks, but the colors appear to be very weird sometimes. Maybe the hue needs fixing.

**Comment by Wuzzy2** [comment]
I have included the new textures! I changed some of the colors, but I gave you the credit.
