### ISSUE TITLE
Broken death animation

### ISSUE THREAD

**Issue by kwadroke** [Wuzzy2/MineClone2-Bugs#338]
Skeleton's death animation repeats. It falls over 3-4 times before disappearing. 

Might be more of a mobs_mc issue. If I need to I can file it over there.

**Comment by kingoscargames** [comment]
https://github.com/maikerumine/mobs_mc/issues/11

**Comment by Wuzzy2** [comment]
I applied a lazy fix for the coming release 0.25.0.
I simply disabled all death animations altogether. It's better that mobs just disappear instead of having this very annoying and broken death animation.

Before I introduce death animations again, the death animations have to work correctly in `amc` or `mobs_mc`.
