### ISSUE TITLE
Banner texture looks incorrect?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#347]
![image](https://user-images.githubusercontent.com/13905392/28752420-74ad9fea-7527-11e7-911c-c1a095e06eaa.png)

Subgame version: 0.25.0

**Comment by Wuzzy2** [comment]
I summon you, @22i!

**Comment by 22i** [comment]
Good find @WSDguy2014  @Wuzzy2 

there was a small texture mapping flip that needed to be done on the lower side of the horizontal - wood
![banner](https://user-images.githubusercontent.com/17874916/28755773-6270251a-7562-11e7-860d-a503bfed543f.png)
also it seem like the problem is with the pixel perfection baner_base texture itself so here is the new texture

baner_base texture https://github.com/22i/amc/blob/master/textures/amc_banner_base.png

banner model https://github.com/22i/amc/blob/master/models/amc_banner.b3d

banner hanging https://github.com/22i/amc/blob/master/models/amc_banner_hanging.b3d

**Comment by 22i** [comment]
with the new modified pixel perfection banner_base texture and new models it should look like this
![banner1](https://user-images.githubusercontent.com/17874916/28755907-699e4450-7564-11e7-94c1-6afa8830b026.png)

**Comment by Wuzzy2** [comment]
@22i: Are you sure it's the PP texture which is to blame here? I looked at Faithful and the texture looks similar.
I'd rather like to avoid having incompatible textures in the repo.

**Comment by 22i** [comment]
test the bannner in minecraft with different resource packs - pixel perfection, faithfull

minecraft default
![minecraft](https://user-images.githubusercontent.com/17874916/28768448-eea2d328-75d7-11e7-97a8-52017ca4936d.png)
faithfull
![faithfull](https://user-images.githubusercontent.com/17874916/28768452-f19576ee-75d7-11e7-8a8f-dba7755b7df4.png)

**Comment by Wuzzy2** [comment]
Sorry, I still have my doubts because you didn't post PP in comparison.

**Comment by Wuzzy2** [comment]
Whatever. I went ahead and just fixed the texture.

**Comment by 22i** [comment]
updated with new pixel perfection and papercutout comparisons

**Comment by Wuzzy2** [comment]
So … is everything fine then? Or do I need to update something again?

And why are there `amc_bannerhanging.b3d` and `amc_banner_hanging.b3d`?

**Comment by 22i** [comment]
i also discovered that minecraft default banner texture was different in minecraft 1.8 than in minecraft 1.11

minecraft 1.8 banner_base
![banner_base](https://user-images.githubusercontent.com/17874916/29486424-8c76b9d6-84e5-11e7-8ad7-2415433d92bc.png)
minecraft 1.11 banner_base
![banner_base](https://user-images.githubusercontent.com/17874916/29486421-6779f382-84e5-11e7-8393-fc53d38030d9.png)

**Comment by 22i** [comment]
when i fixed the model i forgot to rename it from amc_bannerhanging.b3d to amc_banner_hanging.b3d so you just need to change the hanging model

banner hanging https://github.com/22i/amc/blob/master/models/amc_banner_hanging.b3d

i checked the standing banner in the mineclone2 and its fine
