### ISSUE TITLE
Changing weather system to miniclime

### ISSUE THREAD

**Issue by azekillDIABLO** [Wuzzy2/MineClone2-Bugs#352]
I have tested mineclone2 weather and I can confirm that my miniclime mod could do a better job. It support multiplayer, it is more accurate than what I've seen (rain in the desert :rofl:) and is very light. It only misses the thunder support, but that not hard to implement I think. Thanks in advance for reviewing my proposition.

**Comment by Wuzzy2** [comment]
Good idea. Too bad it doesn't have thunder yet.

But the current weather mod is pretty bad anyway, so I should switch.

**Comment by azekillDIABLO** [comment]
Now has thunder in it! But could you explain me what is wrong with the license? cuz' i don't catch a thing of what you said.

**Comment by Wuzzy2** [comment]
The miniclime mod is garbage, it is very inefficient and eats away my CPU for no reason.
It has weather modes I don't need and the weather is linked to the time of day. The weather is very loud since it just spawns sounds over and over again.
Sorry, the quality is way too low. It would be easier for me to just start over than to adapt miniclime.

Note: There are no license issues.
