### ISSUE TITLE
Comparator implementation

### ISSUE THREAD

**Issue by ex-bart** [Wuzzy2/MineClone2-Bugs#381]
This is adapted from mesecons_delayer, with influence by mcl_hoppers.
Comparator textures were taken from the Pixel Perfection V3.6 texture pack,
side texture was adapted from mesecons_delayer.

This works:
- Subtract mode: output = back_input - max(side_inputs)
- Compare mode: output = back_input
  (side inputs have no effect since mesecon has no power levels)
- Probing of container inventories
  (although it may take up to 1s to notice changes)

This is TODO:
- Probing of block/object state other than containers: item frame, cauldron,
  jukebox, cake, plus some other things that aren't even implemented yet.
- Probing through solid blocks.
- Side input should only be accepted from wires, repeaters, comparators, and
  redstone blocks.  Currently it is accepted from things like torches, too.

---

I'm not quite sure how to get the patch to you.  Here is one generated with `git format-patch -k`:
[comparator.txt](https://github.com/Wuzzy2/MineClone2-Bugs/files/1254316/comparator.txt)

See also: #353.

**Comment by Wuzzy2** [comment]
Great! This is the kind of contribution I highly appreciate, even if it is still very incomplete. Good coding style, sane and simple implementation, use of existing APIs.

Sending me patches like this is fine. Just make sure to upload it anywhere where I can access it.

Complaints:
* Your mod created 3 redundant help entries for the other modes of redstone comparators. Use `_doc_items_create_entry=false` to suppress entries
* I prefer mod names representing items to use the plural form, so `mcl_comparators` in this case
* Minor problem with top texture, the a stone pixel changes when you rightclick it
* I have a hard time in understanding the help, it feels incomplete and I couldn't understand it without MC WIki. I suppose players will not understand it at all. Probably needs a complete rewrite, it is important to cover all different modes of operation and use cases.

I have fixed the first 3 complains and included your mod almost verbatim into MCL2! Thank you! I want to personally handle the fourth complaint, too, after this item has become really useful.
Because of the lack of power levels in MCL2, the use of this item is rather limited, so I marked it as “WIP” in-game.

Closing because your mod has been included.

**Comment by Wuzzy2** [comment]
About “querying” the redstone output of other nodes: A first idea I have is to implement this in a way which is generic and extensible with no explicit handling code for specific node in `mcl_comparators` itself. Maybe with a `_on_compare` node callback. That way, the comparator mod does not have to “know” every node it support.
`mcl_dispensers` is an example of what *not* to do (has currently WAY too many explicit checks, I plan to refactor this as soon I start working on redstone stuff seriously).

Note I do not want to bother too much about comparators for now, as MCL2 does not even get the redstone basics right (yet).
