### ISSUE TITLE
More Minecraft feeling texture pack (project maybe?)

### ISSUE THREAD

**Issue by tobyplowy** [Wuzzy2/MineClone2-Bugs#385]
@Wuzzy2 So I had a long think about this but I would be interested in making a Minecraft style texture pack for mineclone2 but only if they become the standard textures of mineclone2 but I Don't Want To Do It Alone maybe @kingoscargames is interested in helping?

@Wuzzy2 what do you think about this do you want this or do you want to keep pixelperfection?

**Comment by Wuzzy2** [comment]
Ugggh. You came a little bit late for this, don't you think?
It was a little bit painful to do the previous texture conversion, I don't feel like repeating this again. Getting all the gameplay stuff done is now much more important.

And personally I like Pixel Perfection. It's not really perfect (that's why I opened a clean-up issue) but still nice, and small improvements are added. In other words, I consider the issue of “textures” being mostly done.

A close resemblance of MC might be nice for somewhere after 1.0.0. But I definitely do not want to think about this now. It is ultra-low priority now that I have 16×16 textures. I will only consider a second full texture conversion if the alternative is **significantly** better. But *please* do not bother me now.

Of course there is always the option of doing a texture pack completely independently without anyone's approval and upload it as an unofficial texture pack in the forums. This is why Minetest supports texture packs, after all.

But if you want to do textures, you can still help out in the “help wanted” issues:
https://github.com/Wuzzy2/MineClone2-Bugs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

I would appreciate 16×16 glazed terracotta textures in Pixel Perfection-like style a lot.

**Comment by kingoscargames** [comment]
> maybe @kingoscargames is interested in helping? 

I'm better at editing textures though.
