### ISSUE TITLE
Nice body

### ISSUE THREAD

**Issue by RonnyBarthmann** [Wuzzy2/MineClone2-Bugs#423]
![scr](https://user-images.githubusercontent.com/32592152/32414633-d6d7a9a8-c22b-11e7-8e4d-905a5c2ab701.png)

**Comment by Wuzzy2** [comment]
Oh noes!

**Comment by Wuzzy2** [comment]
Well, shit. Looks like I screwed up when updating the pig models.

Does it occour with *new* pigs (when they spawn), or do only old pigs look like this?

If its only with new pigs, I don't consider this to be a problem, because these pigs will go away with time. Just kill this poor fellow, new pigs shouldn't look like this.

**Comment by kingoscargames** [comment]
I had the same issue.
> Does it occour with new pigs (when they spawn), or do only old pigs look like this?

As far as i know only with some old pigs.

**Comment by RonnyBarthmann** [comment]
yes, when i walked in new areas, the pigs looked good again
should therefore only affect the old ones
