### ISSUE TITLE
Maximum build height 256?

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#86]
There is no limit build height y for that.

**Comment by Wuzzy2** [comment]
I decided to leave the build height as-is because it has zero gameplay relevance and only adds frustration in creative mode.
This means you can currently build up to ca. Y=30900.

It is pretty clear this limit only exists for technical reasons, not gameplay reasons and in the history of Minecraft the limit has been raised once and I'm pretty sure they would raise the limit again if they could.

This is one of the few cases where I intentionally go directly against a Minecraft behaviour.
