### ISSUE TITLE
Suffocation on leaves in subgame version 0.12.1

### ISSUE THREAD

**Issue by WSDguy2014** [Wuzzy2/MineClone2-Bugs#95]
How the heck i'm taking damage from suffocation for leaves? Because it's used to prevent using an X-ray glitch exploit in survival mode?

**Comment by Wuzzy2** [comment]
OK, so according to Minecraft Wiki, suffocation happens in opaque blocks and leaves don't count as opaque. So this issue is valid.
The definition of “opaque” in Minecraft is a bit weird so I guess I just use that to determine which blocks suffocate you. That way, I should get a pretty precise re-implementation of Minecraft behaviour.

But wait, does this also mean that glass should not suffocate you? Strange.

**Comment by WSDguy2014** [comment]
> does this also mean that glass should not suffocate you?

Yes, i tested it using this:
![image](https://cloud.githubusercontent.com/assets/13905392/23302912/aa8c24fa-fa99-11e6-8963-fddf3ff59cc4.png)
And it suffocate too.
![image](https://cloud.githubusercontent.com/assets/13905392/23302949/d79e01fc-fa99-11e6-8f11-13a6ef220dc5.png)
I tested other glass blocks and also suffocate too.

**Comment by Wuzzy2** [comment]
Fixed!
